In [1]:
import pandas as pd

In [5]:
filepaths = [
    '../data/2019/Complications and Deaths - National.csv',
    '../data/2020/qqw3-t4ie.csv',
    '../data/2021/Complications_and_Deaths-National.csv',
    '../data/2022/Complications_and_Deaths-National.csv',
    '../data/2023/Complications_and_Deaths-National.csv',
    '../data/2024/Complications_and_Deaths-National.csv',
    '../data/2025/Complications_and_Deaths-National.csv',
    '../data/2026/Complications_and_Deaths-National.csv',
]

In [8]:
# check columns
col_sets = []
for fp in filepaths:
    df = pd.read_csv(fp)
    cols = set(df.columns.tolist())
    col_sets.append(cols)

all_equal = all(s == col_sets[0] for s in col_sets)
all_equal

True

In [9]:
# check shape
for fp in filepaths:
    print(fp)
    df = pd.read_csv(fp)
    print(df.shape)
# more rows in 2025 and 2026

../data/2019/Complications and Deaths - National.csv
(19, 10)
../data/2020/qqw3-t4ie.csv
(19, 10)
../data/2021/Complications_and_Deaths-National.csv
(19, 10)
../data/2022/Complications_and_Deaths-National.csv
(19, 10)
../data/2023/Complications_and_Deaths-National.csv
(19, 10)
../data/2024/Complications_and_Deaths-National.csv
(19, 10)
../data/2025/Complications_and_Deaths-National.csv
(20, 10)
../data/2026/Complications_and_Deaths-National.csv
(20, 10)

In [13]:
# check measures
measure_id_sets = []

for fp in filepaths:
    print(fp)
    df = pd.read_csv(fp)
    mids = set(df['Measure ID'].tolist())
    measure_id_sets.append(mids)

all_equal = all(s == measure_id_sets[0] for s in measure_id_sets)
all_equal

../data/2019/Complications and Deaths - National.csv
../data/2020/qqw3-t4ie.csv
../data/2021/Complications_and_Deaths-National.csv
../data/2022/Complications_and_Deaths-National.csv
../data/2023/Complications_and_Deaths-National.csv
../data/2024/Complications_and_Deaths-National.csv
../data/2025/Complications_and_Deaths-National.csv
../data/2026/Complications_and_Deaths-National.csv

False

In [14]:
df = pd.read_csv('../data/2024/Complications_and_Deaths-National.csv')
df['Measure ID'].tolist()

['COMP_HIP_KNEE',
 'MORT_30_AMI',
 'MORT_30_CABG',
 'MORT_30_COPD',
 'MORT_30_HF',
 'MORT_30_PN',
 'MORT_30_STK',
 'PSI_03',
 'PSI_04',
 'PSI_06',
 'PSI_08',
 'PSI_09',
 'PSI_10',
 'PSI_11',
 'PSI_12',
 'PSI_13',
 'PSI_14',
 'PSI_15',
 'PSI_90']

In [15]:
df = pd.read_csv('../data/2025/Complications_and_Deaths-National.csv')
df['Measure ID'].tolist()

['COMP_HIP_KNEE',
 'Hybrid_HWM',
 'MORT_30_AMI',
 'MORT_30_CABG',
 'MORT_30_COPD',
 'MORT_30_HF',
 'MORT_30_PN',
 'MORT_30_STK',
 'PSI_03',
 'PSI_04',
 'PSI_06',
 'PSI_08',
 'PSI_09',
 'PSI_10',
 'PSI_11',
 'PSI_12',
 'PSI_13',
 'PSI_14',
 'PSI_15',
 'PSI_90']

In [16]:
# look for NaNs
for fp in filepaths:
    print(fp)
    df = pd.read_csv(fp)
    print(df.isna().sum())

../data/2019/Complications and Deaths - National.csv
Measure ID                      0
Measure Name                    0
National Rate                   0
Number of Hospitals Worse       0
Number of Hospitals Same        0
Number of Hospitals Better      0
Number of Hospitals Too Few     0
Footnote                       19
Start Date                      0
End Date                        0
dtype: int64
../data/2020/qqw3-t4ie.csv
Measure ID                      0
Measure Name                    0
National Rate                   0
Number of Hospitals Worse       0
Number of Hospitals Same        0
Number of Hospitals Better      0
Number of Hospitals Too Few     0
Footnote                       19
Start Date                      0
End Date                        0
dtype: int64
../data/2021/Complications_and_Deaths-National.csv
Measure ID                      0
Measure Name                    0
National Rate                   0
Number of Hospitals Worse       0
Number of Hospitals Same        0
Number of Hospitals Better      0
Number of Hospitals Too Few     0
Footnote                       19
Start Date                      0
End Date                        0
dtype: int64
../data/2022/Complications_and_Deaths-National.csv
Measure ID                     0
Measure Name                   0
National Rate                  0
Number of Hospitals Worse      0
Number of Hospitals Same       0
Number of Hospitals Better     0
Number of Hospitals Too Few    0
Footnote                       6
Start Date                     0
End Date                       0
dtype: int64
../data/2023/Complications_and_Deaths-National.csv
Measure ID                      0
Measure Name                    0
National Rate                   0
Number of Hospitals Worse       0
Number of Hospitals Same        0
Number of Hospitals Better      0
Number of Hospitals Too Few     0
Footnote                       19
Start Date                      0
End Date                        0
dtype: int64
../data/2024/Complications_and_Deaths-National.csv
Measure ID                      0
Measure Name                    0
National Rate                   0
Number of Hospitals Worse       0
Number of Hospitals Same        0
Number of Hospitals Better      0
Number of Hospitals Too Few     0
Footnote                       19
Start Date                      0
End Date                        0
dtype: int64
../data/2025/Complications_and_Deaths-National.csv
Measure ID                      0
Measure Name                    0
National Rate                   0
Number of Hospitals Worse       0
Number of Hospitals Same        0
Number of Hospitals Better      0
Number of Hospitals Too Few     0
Footnote                       20
Start Date                      0
End Date                        0
dtype: int64
../data/2026/Complications_and_Deaths-National.csv
Measure ID                      0
Measure Name                    0
National Rate                   0
Number of Hospitals Worse       0
Number of Hospitals Same        0
Number of Hospitals Better      0
Number of Hospitals Too Few     0
Footnote                       20
Start Date                      0
End Date                        0
dtype: int64

In [17]:
df = pd.read_csv('../data/2026/Complications_and_Deaths-National.csv')
df

,Measure ID,Measure Name,National Rate,Number of Hospitals Worse,Number of Hospitals Same,Number of Hospitals Better,Number of Hospitals Too Few,Footnote,Start Date,End Date
0,COMP_HIP_KNEE,Rate of complications for hip/knee replacement...,4.10,8,1706,6,1387,NaN,04/01/2023,03/31/2025
1,Hybrid_HWM,Hybrid Hospital-Wide All-Cause Risk Standardiz...,3.90,412,3527,422,250,NaN,07/01/2024,06/30/2025
2,MORT_30_AMI,Death rate for heart attack patients,11.90,3,1941,9,1841,NaN,07/01/2022,06/30/2025
3,MORT_30_CABG,Death rate for CABG surgery patients,2.40,4,859,1,217,NaN,07/01/2022,06/30/2025
4,MORT_30_COPD,Death rate for COPD patients,8.60,10,2638,12,1807,NaN,07/01/2022,06/30/2025
5,MORT_30_HF,Death rate for heart failure patients,11.10,38,2964,106,1388,NaN,07/01/2022,06/30/2025
6,MORT_30_PN,Death rate for pneumonia patients,15.20,84,3529,130,822,NaN,07/01/2022,06/30/2025
7,MORT_30_STK,Death rate for stroke patients,11.90,52,2304,95,1468,NaN,07/01/2023,06/30/2025
8,PSI_03,Pressure ulcer rate,0.63,181,2950,49,61,NaN,07/01/2022,06/30/2024
9,PSI_04,Death rate among surgical inpatients with seri...,173.30,56,1429,45,1045,NaN,07/01/2022,06/30/2024
10,PSI_06,Iatrogenic pneumothorax rate,0.21,14,3204,0,33,NaN,07/01/2022,06/30/2024
11,PSI_08,In-hospital fall-associated fracture rate,0.27,11,3205,1,35,NaN,07/01/2022,06/30/2024
12,PSI_09,Postoperative hemorrhage or hematoma rate,2.34,29,2857,6,152,NaN,07/01/2022,06/30/2024
13,PSI_10,Postoperative acute kidney injury requiring di...,1.67,21,2467,3,406,NaN,07/01/2022,06/30/2024
14,PSI_11,Postoperative respiratory failure rate,9.42,102,2362,36,408,NaN,07/01/2022,06/30/2024
15,PSI_12,Perioperative pulmonary embolism or deep vein ...,3.52,63,2825,12,145,NaN,07/01/2022,06/30/2024
16,PSI_13,Postoperative sepsis rate,5.27,37,2383,22,419,NaN,07/01/2022,06/30/2024
17,PSI_14,Postoperative wound dehiscence rate,1.77,8,2496,0,426,NaN,07/01/2022,06/30/2024
18,PSI_15,Abdominopelvic accidental puncture or lacerati...,1.06,25,2813,2,203,NaN,07/01/2022,06/30/2024
19,PSI_90,CMS Medicare PSI 90: Patient safety and advers...,1.00,163,2765,61,Not Available,NaN,07/01/2022,06/30/2024

In [24]:
df = pd.read_csv('../data/2022/Complications_and_Deaths-National.csv')
df

,Measure ID,Measure Name,National Rate,Number of Hospitals Worse,Number of Hospitals Same,Number of Hospitals Better,Number of Hospitals Too Few,Footnote,Start Date,End Date
0,COMP_HIP_KNEE,Rate of complications for hip/knee replacement...,2.4,24,2478,28,915,NaN,04/01/2018,03/31/2021
1,MORT_30_AMI,Death rate for heart attack patients,12.4,14,2014,19,1917,NaN,07/01/2018,06/30/2021
2,MORT_30_CABG,Death rate for CABG surgery patients,2.9,12,903,7,206,NaN,07/01/2018,06/30/2021
3,MORT_30_COPD,Death rate for COPD patients,8.4,38,2956,25,1539,NaN,07/01/2018,06/30/2021
4,MORT_30_HF,Death rate for heart failure patients,11.3,109,2988,195,1285,NaN,07/01/2018,06/30/2021
5,MORT_30_PN,Death rate for pneumonia patients,Not Available,Not Available,Not Available,Not Available,Not Available,5.0,07/01/2018,06/30/2021
6,MORT_30_STK,Death rate for stroke patients,13.6,53,2075,79,1912,NaN,07/01/2018,06/30/2021
7,PSI_03,Pressure ulcer rate,Not Available,Not Available,Not Available,Not Available,Not Available,5.0,07/01/2019,06/30/2021
8,PSI_04,Death rate among surgical inpatients with seri...,Not Available,Not Available,Not Available,Not Available,Not Available,5.0,07/01/2019,06/30/2021
9,PSI_06,Iatrogenic pneumothorax rate,Not Available,Not Available,Not Available,Not Available,Not Available,5.0,07/01/2019,06/30/2021
10,PSI_08,In-hospital fall with hip fracture rate,Not Available,Not Available,Not Available,Not Available,Not Available,5.0,07/01/2019,06/30/2021
11,PSI_09,Postoperative hemorrhage or hematoma rate,Not Available,Not Available,Not Available,Not Available,Not Available,5.0,07/01/2019,06/30/2021
12,PSI_10,Postoperative acute kidney injury requiring di...,Not Available,Not Available,Not Available,Not Available,Not Available,5.0,07/01/2019,06/30/2021
13,PSI_11,Postoperative respiratory failure rate,Not Available,Not Available,Not Available,Not Available,Not Available,5.0,07/01/2019,06/30/2021
14,PSI_12,Perioperative pulmonary embolism or deep vein ...,Not Available,Not Available,Not Available,Not Available,Not Available,5.0,07/01/2019,06/30/2021
15,PSI_13,Postoperative sepsis rate,Not Available,Not Available,Not Available,Not Available,Not Available,5.0,07/01/2019,06/30/2021
16,PSI_14,Postoperative wound dehiscence rate,Not Available,Not Available,Not Available,Not Available,Not Available,5.0,07/01/2019,06/30/2021
17,PSI_15,Abdominopelvic accidental puncture or lacerati...,Not Available,Not Available,Not Available,Not Available,Not Available,5.0,07/01/2019,06/30/2021
18,PSI_90,CMS Medicare PSI 90: Patient safety and advers...,Not Available,Not Available,Not Available,Not Available,Not Available,5.0,07/01/2019,06/30/2021

In [45]:
df = pd.read_csv(filepaths[8])
df

IndexError: list index out of range